param([string]$OutDir)

$ErrorActionPreference = 'Stop'
$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'

# family query => subsets to keep
$families = [ordered]@{
  'Cormorant+Garamond:ital,wght@0,500..700;1,500..700' = @('latin','latin-ext','cyrillic')
  'Literata:ital,opsz,wght@0,7..72,400..600;1,7..72,400..600' = @('latin','latin-ext','cyrillic')
  'Inter:wght@400..700' = @('latin','latin-ext','cyrillic')
  'Noto+Naskh+Arabic:wght@400..700' = @('arabic')
  'Amiri+Quran' = @('arabic')
  'Noto+Serif+Bengali:wght@400..600' = @('bengali')
  'Noto+Nastaliq+Urdu:wght@400..700' = @('arabic')
}

New-Item -ItemType Directory -Force $OutDir | Out-Null
$css = New-Object System.Text.StringBuilder
[void]$css.AppendLine('/* Self-hosted from Google Fonts, all under the SIL Open Font License 1.1 (see OFL-*.txt). Generated by website/tools/fetch-fonts.ps1. */')

foreach ($query in $families.Keys) {
  $keep = $families[$query]
  $url = "https://fonts.googleapis.com/css2?family=$query&display=swap"
  $resp = Invoke-WebRequest -Uri $url -UserAgent $ua -UseBasicParsing
  $text = $resp.Content
  $blocks = [regex]::Matches($text, '/\*\s*(?<subset>[\w-]+)\s*\*/\s*(?<face>@font-face\s*\{[^}]*\})')
  foreach ($b in $blocks) {
    $subset = $b.Groups['subset'].Value
    if ($keep -notcontains $subset) { continue }
    $face = $b.Groups['face'].Value
    $family = [regex]::Match($face, "font-family:\s*'([^']+)'").Groups[1].Value
    $style = [regex]::Match($face, 'font-style:\s*(\w+)').Groups[1].Value
    $src = [regex]::Match($face, 'url\((?<u>[^)]+)\)').Groups['u'].Value
    $slug = ($family -replace '\s', '') + '-' + $style + '-' + $subset + '.woff2'
    Invoke-WebRequest -Uri $src -UserAgent $ua -OutFile (Join-Path $OutDir $slug) -UseBasicParsing
    $face = $face -replace 'url\([^)]+\)', "url(/fonts/$slug)"
    [void]$css.AppendLine("/* $family $style $subset */")
    [void]$css.AppendLine($face)
    Write-Host "$slug"
  }
}

Set-Content -Path (Join-Path $OutDir 'fonts.css') -Value $css.ToString() -Encoding utf8
