import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../app/providers.dart';
import '../../domain/entities/enums.dart';
import '../../domain/entities/user_preferences.dart';
import '../../shared/theme/app_colors.dart';
import '../../shared/theme/app_spacing.dart';
import '../../shared/theme/app_typography.dart';
import '../../shared/widgets/app_page.dart';
import '../../shared/widgets/settings_group.dart';
import 'settings_labels.dart';

/// Which language(s) an ayah is shown in, and whether to show a
/// transliteration alongside the Arabic.
class ReadingSettingsScreen extends ConsumerWidget {
  const ReadingSettingsScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final UserPreferences preferences = ref.watch(userPreferencesProvider);
    final AppColors colors = context.colors;

    return AppPage(
      title: 'Reading',
      showBackButton: true,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          SettingsGroup(
            title: 'Ayah text',
            children: <Widget>[
              for (final LanguageMode mode in LanguageMode.values)
                ChoiceRow<LanguageMode>(
                  label: SettingsLabels.language(mode),
                  description: _description(mode),
                  value: mode,
                  groupValue: preferences.languageMode,
                  onChanged: (LanguageMode value) => ref
                      .read(userPreferencesProvider.notifier)
                      .update(preferences.copyWith(languageMode: value)),
                ),
            ],
          ),
          const SizedBox(height: AppSpacing.xl),
          SettingsGroup(
            title: 'Transliteration',
            children: <Widget>[
              SettingsRow(
                label: 'Show transliteration',
                description: 'A Latin-script rendering of the Arabic, shown '
                    'only where the edition you are reading carries one.',
                trailing: Switch(
                  value: preferences.showTransliteration,
                  onChanged: (bool value) => ref
                      .read(userPreferencesProvider.notifier)
                      .update(
                        preferences.copyWith(showTransliteration: value),
                      ),
                ),
              ),
            ],
          ),
          const SizedBox(height: AppSpacing.xl),
          Text(
            'When both are shown, the Arabic is displayed first, followed by '
            'the translation. Nothing here is generated by the app: an ayah '
            'shows only what the edition you installed actually contains.',
            style: AppTypography.reference.copyWith(
              color: colors.textSecondary,
              height: 1.6,
            ),
          ),
        ],
      ),
    );
  }

  static String? _description(LanguageMode mode) {
    switch (mode) {
      case LanguageMode.translation:
        return 'Translation only.';
      case LanguageMode.arabic:
        return 'The Arabic only.';
      case LanguageMode.both:
        return 'Arabic first, then the translation.';
    }
  }
}
